### ISSUE TITLE
Clean up `TODO(euclid migration)`

### ISSUE THREAD

**Issue by kpreid** [kpreid/all-is-cubes#542]
Just a few items remaining as of 8392123c73293109df4aa1770e342e77ca4df8f9:

* [x] Should the `Aab` type be replaced with `euclid::Box3D`? No, it should not, so it can enforce not being reversed.
* [ ] Should the `GridMatrix` type be replaced?
* [ ] Interface of `GridMatrix` has residual design from `cgmath::Transform`.

**Comment by kpreid** [comment]
Decided not to do anything further. Commit d13013c114900cce2c2a1a5128e5388bcf1fff76 removes all occurrences of “TODO(euclid migration)”.
